on:
  workflow_dispatch:

jobs:
  galaxy-deployment:
    runs-on: ubuntu-latest
    name: Deployment to Galaxy
    steps:
      - uses: actions/checkout@v4

      - name: Install meteor
        run: npx meteor

      - name: Install dependencies
        run: npm install

      - name: Install expect
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install expect

      - name: Galaxy login
        working-directory: ./scripts
        env:
          GALAXY_USERNAME: ${{ secrets.GALAXY_USERNAME }}
          GALAXY_PASSWORD: ${{ secrets.GALAXY_PASSWORD }}
        run: |
          export PATH="/home/runner/.meteor:$PATH"
          chmod +x ./galaxy-login.sh
          ./galaxy-login.sh

      - name: Deploy
        run: |
          export PATH="/home/runner/.meteor:$PATH"
          meteor deploy testdeployment1239.meteorapp.com --free --mongo