on:
  push:
    branches:
      - shen-spike
  workflow_dispatch:

jobs:
  galaxy-deployment:
    runs-on: ubuntu-latest
    name: Deployment to Galaxy
    steps:
      - uses: actions/checkout@v4
      - name: Install meteor
        run: npx meteor
      - name: Deploy
        env:
          GALAXY_USERNAME: ${{ secrets.GALAXY_USERNAME }}
          GALAXY_PASSWORD: ${{ secrets.GALAXY_PASSWORD }}
        run: |
          export PATH=/home/runner/.meteor:$PATH
          printf "$GALAXY_USERNAME\n$GALAXY_PASSWORD" | meteor login
          meteor deploy testdeployment1239.meteorapp.com --free --mongo