on:
  push:
    branches:
      - shen-spike
  workflow_dispatch:

jobs:
  galaxy-deployment:
    runs-on: ubuntu-latest
    name: Deployment to Galaxy
    steps:
      - uses: actions/checkout@v4
      - name: Install meteor
        run: npx meteor
      - name: Deploy
        env:
          METEOR_DEPLOY_KEY: ${{ secrets.METEOR_DEPLOY_KEY }}
        run: |
          echo $METEOR_DEPLOY_KEY > $GITHUB_WORKSPACE/deploy_secret.json
          export PATH=/home/runner/.meteor:$PATH
          export METEOR_SESSION_FILE=$GITHUB_WORKSPACE/deploy_secret.json
          meteor deploy testdeployment123.meteorapp.com --free --mongo