on:
  push:
    branches:
      - shen-spike
  workflow_dispatch:

jobs:
  galaxy-deployment:
    runs-on: ubuntu-latest
    name: Deployment to Galaxy
    steps:
      - uses: actions/checkout@v4
      - name: Install meteor
        run: npx meteor
      - name: Deploy
        run: |
          export PATH=/home/runner/.meteor:$PATH 
          METEOR_SESSION_FILE="$GITHUB_WORKSPACE/deploy_token.json" meteor deploy testdeployment123.meteorapp.com --free --mongo